version: "3"
services:
  app:
    container_name: renewable-api
    image: renewableapi:latest
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8080:8080
    restart: unless-stopped

